"""
Anamnesis type definitions.

This module exports all type definitions for the Anamnesis semantic code analysis system.
"""

# Core types
from .core import (
    AnalyzedConcept,
    AstNode,
    CodebaseAnalysisResult,
    ComplexityMetrics,
    ConceptEvolution,
    ConceptRelationship,
    ConceptSummary,
    LearnedConcept,
    LearnedPattern,
    LineRange,
    ParseResult,
    RelationshipType,
    SemanticConcept,
    SemanticConceptType,
    Symbol,
    TechnicalDebtLevel,
)

# Error types
from .errors import (
    AnamnesisError,
    ConfigurationError,
    DatabaseError,
    ErrorCode,
    ErrorFactory,
    ExecutionError,
    LearningError,
    MCPErrorCode,
    MCPErrorUtils,
    ResourceError,
    SystemError,
    ValidationError,
)

# Pattern types
from .patterns import (
    AnalyzedPattern,
    DeveloperPattern,
    PatternConstraint,
    PatternContent,
    PatternExample,
    PatternSummary,
    PatternType,
    PatternVariable,
    RelevantPattern,
)

# Analysis types
from .analysis import (
    AIInsight,
    CodebaseAnalysis,
    DirectoryStructure,
    EntryPoint,
    FeatureMap,
    FeatureMapResult,
    FileIntelligence,
    FileMetadata,
    KeyDirectory,
    ProjectDecision,
    WorkSession,
)

# Guard functions
from .guards import (
    is_analyzed_concept,
    is_ast_node,
    is_complexity_metrics,
    is_concept_relationship,
    is_developer_pattern,
    is_dict_with_string_keys,
    is_line_range,
    is_non_empty_string,
    is_parse_result,
    is_pattern_example,
    is_semantic_concept,
    is_string_array,
    is_symbol,
    is_valid_confidence,
    is_valid_frequency,
    safe_get,
    validate_required_fields,
)

# MCP response types
from .mcp_responses import (
    AnalysisSummary,
    AnalyzeCodebaseResponse,
    AutoLearnResponse,
    CodingApproach,
    CodingApproachResponse,
    CodingStyle,
    ComponentStatus,
    ContributeInsightsResponse,
    CurrentWork,
    DeveloperProfile,
    DeveloperProfileResponse,
    HealthCheck,
    HealthCheckResponse,
    IntelligenceMetrics,
    IntelligenceMetricsResponse,
    LearnCodebaseResponse,
    LearningStatus,
    MCPResponse,
    PatternRecommendation,
    PatternRecommendationsResponse,
    PerformanceMetrics,
    PerformanceStatusResponse,
    PreferredPattern,
    ProjectBlueprintResponse,
    SearchCodebaseResponse,
    SearchResult,
    SemanticInsight,
    SemanticInsightsResponse,
    SystemStatusResponse,
)

# Response envelope types
from .response_envelope import (
    ErrorCategory,
    Pagination,
    RecoveryAction,
    ResponseError,
    ResponseMeta,
    StandardResponse,
    is_error_category,
    is_pagination,
    is_response_error,
    is_standard_response,
)

# File change types
from .file_change import (
    ChangeAnalysis,
    FileChange,
    FileChangeType,
    FileStats,
    PatternAnalysisResult,
    WatcherOptions,
)

# Config types
from .config import (
    EXTENSION_TO_LANGUAGE,
    IGNORED_DIRECTORIES,
    IGNORED_FILE_NAMES,
    IGNORED_FILE_SUFFIXES,
    AnalysisConfig,
    AnamnesisConfig,
    CacheConfig,
    DatabaseConfig,
    EngineConfig,
    LoggingConfig,
    WatcherConfig,
)

__all__ = [
    # Core types
    "LineRange",
    "SemanticConceptType",
    "RelationshipType",
    "TechnicalDebtLevel",
    "ConceptRelationship",
    "ConceptEvolution",
    "SemanticConcept",
    "ConceptSummary",
    "AnalyzedConcept",
    "ComplexityMetrics",
    "AstNode",
    "Symbol",
    "ParseResult",
    "CodebaseAnalysisResult",
    "LearnedConcept",
    "LearnedPattern",
    # Error types
    "MCPErrorCode",
    "ErrorCode",
    "AnamnesisError",
    "ValidationError",
    "ResourceError",
    "LearningError",
    "ExecutionError",
    "ConfigurationError",
    "SystemError",
    "DatabaseError",
    "ErrorFactory",
    "MCPErrorUtils",
    # Pattern types
    "PatternType",
    "PatternVariable",
    "PatternConstraint",
    "PatternContent",
    "PatternExample",
    "DeveloperPattern",
    "PatternSummary",
    "AnalyzedPattern",
    "RelevantPattern",
    # Analysis types
    "FileMetadata",
    "DirectoryStructure",
    "CodebaseAnalysis",
    "FileIntelligence",
    "AIInsight",
    "FeatureMap",
    "EntryPoint",
    "KeyDirectory",
    "WorkSession",
    "ProjectDecision",
    "FeatureMapResult",
    # Guards
    "is_line_range",
    "is_complexity_metrics",
    "is_ast_node",
    "is_symbol",
    "is_parse_result",
    "is_semantic_concept",
    "is_concept_relationship",
    "is_analyzed_concept",
    "is_developer_pattern",
    "is_pattern_example",
    "is_non_empty_string",
    "is_valid_confidence",
    "is_valid_frequency",
    "is_string_array",
    "is_dict_with_string_keys",
    "validate_required_fields",
    "safe_get",
    # MCP response types
    "LearningStatus",
    "AnalysisSummary",
    "AnalyzeCodebaseResponse",
    "SearchResult",
    "SearchCodebaseResponse",
    "ProjectBlueprintResponse",
    "LearnCodebaseResponse",
    "SemanticInsight",
    "SemanticInsightsResponse",
    "PatternRecommendation",
    "PatternRecommendationsResponse",
    "CodingApproach",
    "CodingApproachResponse",
    "PreferredPattern",
    "CodingStyle",
    "CurrentWork",
    "DeveloperProfile",
    "DeveloperProfileResponse",
    "ContributeInsightsResponse",
    "AutoLearnResponse",
    "ComponentStatus",
    "SystemStatusResponse",
    "IntelligenceMetrics",
    "IntelligenceMetricsResponse",
    "PerformanceMetrics",
    "PerformanceStatusResponse",
    "HealthCheck",
    "HealthCheckResponse",
    "MCPResponse",
    # Response envelope types
    "ErrorCategory",
    "RecoveryAction",
    "ResponseMeta",
    "Pagination",
    "ResponseError",
    "StandardResponse",
    "is_error_category",
    "is_standard_response",
    "is_response_error",
    "is_pagination",
    # File change types
    "FileChangeType",
    "FileStats",
    "FileChange",
    "WatcherOptions",
    "ChangeAnalysis",
    "PatternAnalysisResult",
    # Config types
    "IGNORED_DIRECTORIES",
    "IGNORED_FILE_SUFFIXES",
    "IGNORED_FILE_NAMES",
    "EXTENSION_TO_LANGUAGE",
    "AnalysisConfig",
    "DatabaseConfig",
    "CacheConfig",
    "LoggingConfig",
    "WatcherConfig",
    "EngineConfig",
    "AnamnesisConfig",
]
